### ISSUE TITLE
Any license required to use this code?

### ISSUE THREAD

**Issue by EmedBooks** [PranoySarkar/OpenPWA#1]
This is a great code and simple ones. Nice way to bring the pwa expirence with download button. Thank you for this code. I am a doctor and have made a website for teaching medical content. Can I copy these files and make my own pwa?  I have tried and it works perfect in my website. Thanks and regards

**Comment by PranoySarkar** [comment]
Yes you can use, modify, redistribute for commercial and non commercial purpose. Best of luck :)

**Comment by EmedBooks** [comment]
Thanks
